export const GAME_SCENE_KEYS = Object.freeze({
    WELCOME_SCENE: 'WELCOME_SCENE',
    BOOT_SCENE: 'BOOT_SCENE',
    OPTION_SCENE: 'OPTION_SCENE',
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    GAME_SCENE: 'GAME_SCENE'
})