export const PLAYER_MOVEMENT_VERTICAL_VELOCITY=200


export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG=0.01

export const MAX_BULLET_SHOOT=10;


export const PLAYER_BULLET_INTERVAL=300;
export const PLAYER_BULLET_SPEED=300;
export const PLAYER_BULLET_LIFESPAN=3;