export const PLAYER_LIVES = 3;
export const PLAYER_HEALTH = 4;
export const PLAYER_BULLET_SPEED = 300;
export const PLAYER_BULLET_INTERVAL = 300;
export const PLAYER_BULLET_LIFESPAN = 3;
export const PLAYER_BULLET_MAX_COUNT = 10;
export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 20;

export const ENEMY_FIGHTER_SCORE = 200;
export const ENEMY_FIGHTER_HEALTH = 2;
export const ENEMY_FIGHTER_MOVEMENT_VERTICAL_VELOCITY = 12;
export const ENEMY_FIGHTER_BULLET_SPEED = -250;
export const ENEMY_FIGHTER_BULLET_INTERVAL = 2000;
export const ENEMY_FIGHTER_BULLET_LIFESPAN = 5;
export const ENEMY_FIGHTER_BULLET_MAX_COUNT = 10;
export const ENEMY_FIGHTER_GROUP_SPAWN_INTERVAL = 6000;
export const ENEMY_FIGHTER_GROUP_SPAWN_START = 3000;

export const ENEMY_SCOUT_SCORE = 100;
export const ENEMY_SCOUT_HEALTH = 2;
export const ENEMY_SCOUT_MOVEMENT_MAX_X = 100;
export const ENEMY_SCOUT_MOVEMENT_VERTICAL_VELOCITY = 10;
export const ENEMY_SCOUT_MOVEMENT_HORIZONTAL_VELOCITY = 9;
export const ENEMY_SCOUT_GROUP_SPAWN_INTERVAL = 5000;
export const ENEMY_SCOUT_GROUP_SPAWN_START = 1000;

export const COMPONENT_MOVEMENT_VERTICAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_VERTICAL_MAX_VELOCITY = 200;
export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 200;

export const CUSTOM_EVENTS = Object.freeze({
    ENEMY_INIT: 'ENEMY_INIT',
    ENEMY_DESTROYED: 'ENEMY_DESTROYED',
    PLAYER_SPAWN:'PLAYER_SPAWN',
    PLAYER_DESTROYED:'PLAYER_DESTROYED',
    GAME_OVER:'GAME_OVER',
    SHIP_HIT:'SHIP_HIT',
    SHIP_SHOOT:'SHIP_SHOOT'
})