export const GAME_IMAGES = Object.freeze({
    DEFAULT_IMAGES: 'DEFAULT_IMAGES',
    GLOBE_IMAGES: 'GLOBE_IMAGES',
    TRANSPARENT_GLASS_CONTAINER_IMAGE: 'TRANSPARENT_GLASS_CONTAINER_IMAGE',
    CURSOR_IMAGES: 'CURSOR_IMAGE',
    STAGE_ONE: 'STAGE_ONE',
    STAGE_TWO: 'STAGE_TWO',
    STAGE_THREE: 'STAGE_THREE',

    PLAYER_SHIP: 'PLAYER_SHIP'

})