export const GAME_IMAGES = Object.freeze({
    DEFAULT_IMAGES: 'DEFAULT_IMAGES',
    GLOBE_IMAGES: 'GLOBE_IMAGES',
    TRANSPARENT_GLASS_CONTAINER_IMAGE: 'TRANSPARENT_GLASS_CONTAINER_IMAGE',
    CURSOR_IMAGES: 'CURSOR_IMAGE',

})